//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionPersonal.WebService.PruebasWeb
{
    public partial class _Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtServicioUrl;

        protected global::System.Web.UI.WebControls.TextBox txtUsuario;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Button btnAutenticar;

        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.Literal litAutenticado;

        protected global::System.Web.UI.WebControls.Literal litMensajeServicio;

        protected global::System.Web.UI.WebControls.Literal litIdUsuario;

        protected global::System.Web.UI.WebControls.Literal litNombreCompleto;

        protected global::System.Web.UI.WebControls.Literal litToken;

        protected global::System.Web.UI.WebControls.Literal litExpira;
    }
}
